name: Continuous Integration Workflow

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Run isort
        uses: jamescurtin/isort-action@master
        with:
          sortPaths: "./src ./tests"

      - name: Run black on source code
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "23.3.0"